services:
  backend:
    build: ./backend-python
    ports:
      - "8000:8000"
    env_file:
      - ./backend-python/.env
    volumes:
      - backend_uploads:/app/uploads
      - chroma_data:/app/chroma_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      BACKEND_URL: http://backend:8000              # for server-side API routes
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8000  # for browser fetch()
    volumes:
      - ./frontend/prisma:/app/prisma
    depends_on:
      - backend

volumes:
  backend_uploads:
  chroma_data:
